apiVersion: apps/v1
kind: Deployment
metadata:
  name: sa-logic
  labels:
    app: sa-logic
spec:
  selector:
    matchLabels:
      app:  sa-logic
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: sa-logic
        version: v1
    spec:
      containers:
        - image: rinormaloku/sentiment-analysis-logic:istio-tracing
          imagePullPolicy: Always
          name: sa-logic
          env:
            - name: JAEGER_HOST
              value: jaeger-agent.istio-system.svc.cluster.local
            - name: JAEGER_SERVICE_NAME
              value: sa-logic
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: sa-logic
  labels:
    app: sa-logic
spec:
  ports:
    - name: http
      port: 80
      targetPort: 5000
  selector:
    app: sa-logic