apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sa-web-app
spec:
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: sa-web-app
    spec:
      containers:
      - image: rinormaloku/sentiment-analysis-web-app:istio-tracing
        imagePullPolicy: Always
        name: sa-web-app
        env:
          - name: SA_LOGIC_API_URL
            value: "http://sa-logic"
          - name: JAEGER_SERVICE_NAME
            value: "sa-web-app"
          - name: JAEGER_AGENT_HOST
            value: "jaeger-agent.istio-system.svc.cluster.local"
          - name: JAEGER_REPORTER_LOG_SPANS
            value: "true"
          - name: JAEGER_SAMPLER_TYPE
            value: "const"
          - name: JAEGER_SAMPLER_PARAM
            value: "1"
        ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: sa-web-app
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: sa-web-app